# cbindgen.toml

language = "C"
include_guard = "DROPBEAR_H"
line_length = 100
tab_width = 4

[parse]
parse_deps = true
include = ["eucalyptus_core"]

[parse.expand]
crates = ["eucalyptus_core", "dropbear_macro"]