[package]
name = "kino-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
wgpu.workspace = true
anyhow.workspace = true
bytemuck.workspace = true
parking_lot.workspace = true
