[package]
name = "dropbear-traits"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
serde.workspace = true
egui.workspace = true
anyhow.workspace = true
hecs.workspace = true
typetag.workspace = true