[package]
name = "dropbear-traits"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
typetag.workspace = true
hecs.workspace = true
log.workspace = true
dyn-hash.workspace = true
anyhow.workspace = true